import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";
import { Nav } from "../components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Watch Stuff",
  description: "Generated by create next app",
};
const scrollbarClasses =
  "scrollbar-thin scrollbar-track-slate-900 scrollbar-thumb-red-800 scrollbar-track-rounded-3xl scrollbar-thumb-rounded-3xl";

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <SpeedInsights />
      <body
        className={twMerge(
          "bg-black px-2 py-4 overflow-x-hidden text-white",
          scrollbarClasses,
          inter.className
        )}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
